version: '2'

services:
  api:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - NODE_ENV=local

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
